import pandas as pd

def Preprocessing(data):
    # Mengubah item name menjadi huruf kecil semua 
    data['item_name'] = data['item_name'].apply(lambda item: item.lower())
    # menghapus spasi ekstra jika ada
    data['item_name'] = data['item_name'].apply(lambda item: item.strip())
    # membuat copyan dataset yang hanya berisikan order_no dan item_name
    data = data[['order_no','item_name']].copy()
    # Ganti nama item
    data['item_name'] = data['item_name'].str.lower().replace({
        'aroma bold 12': 'Rokok',
        'aroma mile 16': 'Rokok',
        'class mild 12': 'Rokok',
        'aroma bold 16':'Rokok',
        'air mineral ron 88' : 'Air Mineral',
        'new lemon tea' : 'Tropical Series',
        'lychee tea' : 'Tropical Series',
        'matcha latte' : 'Tropical Series',
        'chocolate malt' : 'Tropical Series',
        'taro' : 'Tropical Series',
        'new red velvet' : 'Tropical Series',
        'royal chocolate' : 'Tropical Series',
        'cappucino latte' : 'Tropical Series',
        'new thai tea' : 'Tropical Series',
        'milk tea' : 'Tropical Series',
        'coffee hazelnut' : 'Tropical Series',
        'coffe choco orange':'Tropical Series',
        'jeruk' : 'Tropical Series',
        'josua':'Tropical Series',
        'dancow coklat':'Tropical Series',
        'dancow putih':'Tropical Series',
        'susu putih':'Tropical Series',
        'susu coklat':'Tropical Series',
        'champion/milo':'Tropical Series',
        'milkshake greentea' : 'Milkshake',
        'milkshake red velvet': 'Milkshake',
        'milkshake':'Milkshake',
        'ice cream mix': 'ice cream',
        'ice cream roti':'ice cream',
        'kopi rempah' : 'Kopi',
        'kopi hitam':'Kopi',
        'kopi coklat (tanpa ampas)': 'Kopi',
        'mie ayam polos' : 'mie ayam',
        'mie ayam pangsit rebus' : 'mie ayam',
        'mie ayam bakso sapi' : 'mie ayam',
        'mie ayam pangsit goreng' : 'mie ayam',
        'mie ayam pangsit mix'  : 'mie ayam',
        'mie ayam komplit pangsit rebus':'mie ayam',
        'mie ayam komplit pangsit goreng':'mie ayam',
        'miyago polos' : 'mie ayam',
        'miyago pangsit rebus' : 'mie ayam',
        'miyago bakso sapi' : 'mie ayam',
        'miyago pangsit goreng' : 'mie ayam',
        'miyago pangsit mix' : 'mie ayam',
        'miyago komplit pangsit rebus':'mie ayam',
        'miyago komplit pangsit goreng': 'mie ayam',
        'bintang redler lemon' : 'Bintang',
        'bintang pilsener original': 'Bintang',
        'bintang crystal':'Bintang',
        'mix max exotic blue': 'mix max',
        'mix max anggur merah':'mix max',
        'mixmax amer': 'mix max',
        'prost alster': 'Prost',
        'prost pilsener': 'Prost',
        'prost lemon':'Prost',
        'prost':'Prost',
        'vodkamix lychee': 'Vodka',
        'vodka long island 275ml': 'Vodka',
        'vodka lychee martini 275ml':'Vodka',
        'iceland leci' : 'Vodka',
        'iceland vodka mix':'Vodka',
        'vodka lychee':'Vodka',
        'vodka mix kamikase':'Vodka',
        'vodka kamikaze': 'Vodka',
        'iceland vodkamix' : 'Vodka',
        'iceland lychee':'Vodka',
        'iceland lychee martini': 'Vodka',
        'iceland vodca mix lychee':'Vodka',
        'vodkamix long island':'Vodka',
        'iceland long island':'Vodka',
        'long island':'Vodka',
        'iceland lycee':'Vodka',
        'indomie tante ':'Indomie',
        'intel keju':'Indomie',
        'mie nyemek':'Indomie',
        'intel':'Indomie',
        'indomie tante':'Indomie',
        'nasi omle5':'Nasi',
        'nasi omelet':'Nasi',
        'nasi  omelet':'Nasi',
        'nasi omlate':'Nasi',
        'nasi omlet':'Nasi',
        'omlet':'Nasi',
        'omelet':'Nasi',
        'nasi goreng':'Nasi',
        'ready eat':'Nasi',
        'nasi add on':'Nasi',
        'teh tawar':'Teh',
        'sale pisang':'Chiki',
        'sale pisang':'Chiki',
    })
    return data
def ExtraPreprocessing(data):
    # Menghitung frekuensi munculnya setiap OrderID
    order_id_counts = data['order_no'].value_counts()
    # Memfilter DataFrame berdasarkan OrderID yang muncul lebih dari satu kali
    data = data[data['order_no'].isin(order_id_counts.index[order_id_counts > 1])]
    return data